### ISSUE TITLE
"licesnse" misspelling on site

### ISSUE THREAD

**Issue by paulirish** [dowjones/intentionjs#14]
> MIT licesnse for everything

:arrow_right: "license" 

<hr>

Congrats on open sourcing this btw! Pretty huge achievement to successfully open source a project (WSJ's first?) in that environment. :clap:

**Comment by everyplace** [comment]
Fixed, thanks Paul. And yeah, being on the html working group for the better part of 2012 certainly made me make an OSS license a requirement for this.

**Comment by paulirish** [comment]
:dancer:
