### ISSUE TITLE
_attrsToSpec fails in IE8 in IE9 dev mode

### ISSUE THREAD

**Issue by mynameisstephen** [dowjones/intentionjs#17]
Hi,

In the IE8 development mode of IE9 the if condition on line 378 fails because specMatch[0] actually equals an empty string.  It might also fail on a real IE8 browser, but I have not tested it.

A possible fix would be to add an || condition to check for an empty string as well.

Stephen

**Comment by 1800joe** [comment]
fixed! thank you!
