### ISSUE TITLE
Finding elements that match current context

### ISSUE THREAD

**Issue by VarinderS** [dowjones/intentionjs#31]
Hi,

Maybe im missing the obvious here, im trying to figure out a way to find all the elements that match current context via event like below

```
intent.on( "image:standard", function() {
    var elements = ... get all elements that match this context;
    elements.callSomeMethod();
});
```

Thanks in advance,

Varinder

**Comment by 1800joe** [comment]
the elements that match a current context are not passed into that event. at the moment you can attach an event to your element with jquery like so:

```
$('#elm').on('intent', function(){...});
```

or you could do a manual query in that function for the elements of that context. I will keep this feature in mind for future releases. thanks!
