### ISSUE TITLE
ie10 support not functional

### ISSUE THREAD

**Issue by everyplace** [dowjones/intentionjs#35]
We have reports from elsewhere of intentions not behaving correctly in ie10. @cortesben said that even the current demos do not work properly in ie10. Considering this is in scope as an actually supported browser, can you please investigate?

http://www.modern.ie/en-us/virtualization-tools/#downloads to get a Win8/ie10 vm. Probably should test in ie11 as well, as the betas are out (and available from the same location).

**Comment by arahman** [comment]
It's seems the current demos/examples do not also with in ie8. Tested in IE10 by changing the browser mode and also using ietester.

**Comment by 1800joe** [comment]
demos need to be synced with latest code, the last release fixed the ie bugs we identified
